name: PHP Syntax Checker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check PHP syntax
      run: ./vendor/bin/php-cs-fixer fix --dry-run --diff
